language: python
dist: xenial

python:
  - 3.6
  - 3.7
  - 3.8


before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install:
  - poetry install

script:
  - poetry run flake8 kira_setup
  - poetry run mypy kira_setup
  - poetry check
  - poetry run pip check
  - poetry run safety check --full-report

notifications:
  email:
    on_success: never
    on_failure: change
