name: Build and publish package

on:
  release:
    types: published
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PROJECT: https://pypi.org/project/kira-setup

jobs:
  build:
    name: Build sdist and wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.13'

      - name: Install poetry
        run: |
          curl -sSL "https://install.python-poetry.org" | python

          # Adding `poetry` to `$PATH`:
          echo "$HOME/.poetry/bin" >> "$GITHUB_PATH"

      - name: Check package metadata
        run: poetry check

      - name: Build sdist and wheel
        run: poetry build

      - name: Upload distributions as workflow artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v4.6.1
        with:
          name: sdist-and-pure-wheel
          path: dist/

  publish:
    name: Publish package to PyPI
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release
      url: ${{ env.PROJECT }}
    permissions:
      id-token: write # Required for PyPI trusted publishing

    steps:
      - name: Download distributions
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v4.1.8
        with:
          name: sdist-and-pure-wheel
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          verbose: true
